external_data_config:
  external_data_csv: data/external/train.csv

raw_data_config: 
  raw_data_csv: data/raw/train.csv
  model_var: ["LIMIT_BAL","SEX","EDUCATION","Marital_Status","AGE","PAY_0","PAY_2","PAY_3","PAY_4","PAY_5","PAY_6","BILL_AMT1","BILL_AMT2","BILL_AMT3","BILL_AMT4","BILL_AMT5","BILL_AMT6","PAY_AMT1","PAY_AMT2","PAY_AMT3","PAY_AMT4","PAY_AMT5","PAY_AMT6","Default_Payment"]
  train_test_split_ratio: 0.3
  target: Default_Payment
  random_state: 40
  new_train_data_csv: data/raw/train_new.csv

processed_data_config:
  train_data_csv: data/processed/churn_train.csv
  test_data_csv:  data/processed/churn_test.csv

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: model_iteration1
  run_name: random_forest
  registered_model_name: random_forest_model
  remote_server_uri: http://localhost:1234
 
random_forest: 
  max_depth: 6
  min_samples_leaf: 5
  min_samples_split: 5
  n_estimators: 100

model_dir: models/model.joblib

model_webapp_dir: webapp/model_webapp_dir/model.joblib

model_monitor:
  target_col_name: target
  monitor_dashboard_html: reports/data_and_target_drift_dashboard.html